version: '3.7'
services:
    neo4j:
      image: neo4j:5.6
      restart: unless-stopped
      build: 
        context: ./neo4j/
      container_name: neo4j
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - ./data:/data
        - ./plugins:/plugins
      environment: 
        - NEO4J_server_memory_pagecache_size=1G
        - NEO4J_server_memory_heap_max__size=1G
        - NEO4J_PLUGINS=["apoc"]
        - NEO4J_AUTH=neo4j/12345678
    
    mongodb:
      image: mongo:5.0
      container_name: mong
      ports:
        - '27017:27017'
      volumes:
        - data_cont:/data/db
      
volumes:
  data_cont: